from typing import List

from pydantic import BaseModel, Field

class YoutubeAnalysisResponse(BaseModel):
    title : str = Field(description="Video title")
    summary : str = Field(description="Short summary of the video")
    key_topics: List[str] = Field(description="Main topics covered in the video")
    recommended_audience : str = Field(description="Who should watch")

class YoutubeRequest(BaseModel):
    url : str

class QuizQuestion(BaseModel):
    question : str = Field(description="A question generated by the video transcript")
    options : List[str] = Field(description="$ answers for the question")
    correct_answer : str = Field(description="Correct Answer")

class QuizResponse(BaseModel):
    title: str
    questions : List[QuizQuestion]